2025-03-05 14:45:39,851 INFO    Thread-2 (_run_job):1914713 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-05 14:45:39,851 INFO    Thread-2 (_run_job):1914713 [wandb_setup.py:_flush():67] Configure stats pid to 1914713
2025-03-05 14:45:39,851 INFO    Thread-2 (_run_job):1914713 [wandb_setup.py:_flush():67] Loading settings from /speech/utkarsh/.config/wandb/settings
2025-03-05 14:45:39,851 INFO    Thread-2 (_run_job):1914713 [wandb_setup.py:_flush():67] Loading settings from /speech/utkarsh/da6401_assignment1/wandb/settings
2025-03-05 14:45:39,851 INFO    Thread-2 (_run_job):1914713 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-05 14:45:39,851 INFO    Thread-2 (_run_job):1914713 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /speech/utkarsh/da6401_assignment1/wandb/run-20250305_144539-jk5younu/logs/debug.log
2025-03-05 14:45:39,851 INFO    Thread-2 (_run_job):1914713 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /speech/utkarsh/da6401_assignment1/wandb/run-20250305_144539-jk5younu/logs/debug-internal.log
2025-03-05 14:45:39,851 INFO    Thread-2 (_run_job):1914713 [wandb_init.py:init():761] calling init triggers
2025-03-05 14:45:39,851 INFO    Thread-2 (_run_job):1914713 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'sigmoid', 'batch_size': 32, 'epochs': 2, 'hidden_layer_size': 32, 'hidden_layers_count': 2, 'learning_rate': 0.0001, 'optimizer': 'sgd', 'weight_decay': 0, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-03-05 14:45:39,851 INFO    Thread-2 (_run_job):1914713 [wandb_init.py:init():784] starting backend
2025-03-05 14:45:39,851 INFO    Thread-2 (_run_job):1914713 [wandb_init.py:init():788] sending inform_init request
2025-03-05 14:45:39,862 INFO    Thread-2 (_run_job):1914713 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-03-05 14:45:39,864 INFO    Thread-2 (_run_job):1914713 [wandb_init.py:init():803] backend started and connected
2025-03-05 14:45:39,865 INFO    Thread-2 (_run_job):1914713 [wandb_run.py:_config_callback():1261] config_cb None None {'activation': 'sigmoid', 'batch_size': 32, 'epochs': 2, 'hidden_layer_size': 32, 'hidden_layers_count': 2, 'learning_rate': 0.0001, 'optimizer': 'sgd', 'weight_decay': 0, 'weight_init': 'random'}
2025-03-05 14:45:39,867 INFO    Thread-2 (_run_job):1914713 [wandb_init.py:init():896] updated telemetry
2025-03-05 14:45:39,944 INFO    Thread-2 (_run_job):1914713 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-03-05 14:45:40,795 INFO    Thread-2 (_run_job):1914713 [wandb_init.py:init():995] starting run threads in backend
2025-03-05 14:45:41,368 INFO    Thread-2 (_run_job):1914713 [wandb_run.py:_console_start():2377] atexit reg
2025-03-05 14:45:41,369 INFO    Thread-2 (_run_job):1914713 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-05 14:45:41,369 INFO    Thread-2 (_run_job):1914713 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-05 14:45:41,369 INFO    Thread-2 (_run_job):1914713 [wandb_run.py:_redirect():2317] Redirects installed.
2025-03-05 14:45:41,370 INFO    Thread-2 (_run_job):1914713 [wandb_init.py:init():1037] run started, returning control to user process
2025-03-05 14:49:56,581 WARNING MsgRouterThr:1914713 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "/speech/utkarsh/miniconda3/envs/valle/lib/python3.10/site-packages/wandb/sdk/interface/router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
  File "/speech/utkarsh/miniconda3/envs/valle/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
  File "/speech/utkarsh/miniconda3/envs/valle/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/speech/utkarsh/miniconda3/envs/valle/lib/python3.10/site-packages/wandb/sdk/interface/router.py", line 70, in message_loop
    msg = self._read_message()
  File "/speech/utkarsh/miniconda3/envs/valle/lib/python3.10/site-packages/wandb/sdk/interface/router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-03-05 14:49:56,582 INFO    MsgRouterThr:1914713 [mailbox.py:close():115] Closing mailbox, abandoning 2 handles.
