Training set: (50000, 784), (50000,)
Validation set: (10000, 784), (10000,)
Test set: (10000, 784), (10000,)

Training with momentum:
Epoch 1/5 - 2.57s - loss: 2.1871 - acc: 0.5146 - val_loss: 16.6788 - val_acc: 0.5171
Epoch 2/5 - 2.83s - loss: 1.8084 - acc: 0.6316 - val_loss: 12.4132 - val_acc: 0.6406
Epoch 3/5 - 2.78s - loss: 1.4449 - acc: 0.6344 - val_loss: 12.3476 - val_acc: 0.6425
Epoch 4/5 - 2.93s - loss: 1.2251 - acc: 0.6831 - val_loss: 10.8763 - val_acc: 0.6851
Epoch 5/5 - 2.97s - loss: 1.0865 - acc: 0.6874 - val_loss: 10.6690 - val_acc: 0.6911
{'train_loss': [2.1870560825073135, 1.8083728754731503, 1.444943221417433, 1.2251067519670031, 1.0865021882785448], 'train_acc': [0.5146, 0.63156, 0.63442, 0.68312, 0.68742], 'val_loss': [16.67877512110237, 12.4132362363309, 12.347612561180568, 10.876260686757373, 10.669028028387912], 'val_acc': [0.5171, 0.6406, 0.6425, 0.6851, 0.6911]}

Test accuracy with momentum: 0.6776
Traceback (most recent call last):
  File "/speech/utkarsh/da6401_assignment1/main_new.py", line 124, in <module>
    main()
  File "/speech/utkarsh/da6401_assignment1/main_new.py", line 101, in main
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'
