2025-03-04 18:08:43,303 INFO    Thread-5 (_run_job):1557667 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-04 18:08:43,303 INFO    Thread-5 (_run_job):1557667 [wandb_setup.py:_flush():67] Configure stats pid to 1557667
2025-03-04 18:08:43,303 INFO    Thread-5 (_run_job):1557667 [wandb_setup.py:_flush():67] Loading settings from /speech/utkarsh/.config/wandb/settings
2025-03-04 18:08:43,303 INFO    Thread-5 (_run_job):1557667 [wandb_setup.py:_flush():67] Loading settings from /speech/utkarsh/da6401_assignment1/wandb/settings
2025-03-04 18:08:43,303 INFO    Thread-5 (_run_job):1557667 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-04 18:08:43,303 INFO    Thread-5 (_run_job):1557667 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /speech/utkarsh/da6401_assignment1/wandb/run-20250304_180843-z0uo1j40/logs/debug.log
2025-03-04 18:08:43,303 INFO    Thread-5 (_run_job):1557667 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /speech/utkarsh/da6401_assignment1/wandb/run-20250304_180843-z0uo1j40/logs/debug-internal.log
2025-03-04 18:08:43,303 INFO    Thread-5 (_run_job):1557667 [wandb_init.py:init():761] calling init triggers
2025-03-04 18:08:43,304 INFO    Thread-5 (_run_job):1557667 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'sigmoid', 'batch_size': 32, 'epochs': 2, 'hidden_layer_size': 128, 'hidden_layers_count': 4, 'learning_rate': 0.001, 'optimizer': 'nadam', 'weight_decay': 0.5, 'weight_init': 'xavier'}
config: {'_wandb': {}}
2025-03-04 18:08:43,304 INFO    Thread-5 (_run_job):1557667 [wandb_init.py:init():784] starting backend
2025-03-04 18:08:43,304 INFO    Thread-5 (_run_job):1557667 [wandb_init.py:init():788] sending inform_init request
2025-03-04 18:08:43,311 INFO    Thread-5 (_run_job):1557667 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-03-04 18:08:43,523 INFO    Thread-5 (_run_job):1557667 [wandb_init.py:init():803] backend started and connected
2025-03-04 18:08:43,524 INFO    Thread-5 (_run_job):1557667 [wandb_run.py:_config_callback():1261] config_cb None None {'activation': 'sigmoid', 'batch_size': 32, 'epochs': 2, 'hidden_layer_size': 128, 'hidden_layers_count': 4, 'learning_rate': 0.001, 'optimizer': 'nadam', 'weight_decay': 0.5, 'weight_init': 'xavier'}
2025-03-04 18:08:43,525 INFO    Thread-5 (_run_job):1557667 [wandb_init.py:init():896] updated telemetry
2025-03-04 18:08:43,550 INFO    Thread-5 (_run_job):1557667 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-03-04 18:08:44,079 INFO    Thread-5 (_run_job):1557667 [wandb_init.py:init():995] starting run threads in backend
2025-03-04 18:08:44,622 INFO    Thread-5 (_run_job):1557667 [wandb_run.py:_console_start():2377] atexit reg
2025-03-04 18:08:44,623 INFO    Thread-5 (_run_job):1557667 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-04 18:08:44,625 INFO    Thread-5 (_run_job):1557667 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-04 18:08:44,625 INFO    Thread-5 (_run_job):1557667 [wandb_run.py:_redirect():2317] Redirects installed.
2025-03-04 18:08:44,627 INFO    Thread-5 (_run_job):1557667 [wandb_init.py:init():1037] run started, returning control to user process
2025-03-04 18:13:11,323 WARNING MsgRouterThr:1557667 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "/speech/utkarsh/miniconda3/envs/valle/lib/python3.10/site-packages/wandb/sdk/interface/router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
  File "/speech/utkarsh/miniconda3/envs/valle/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
  File "/speech/utkarsh/miniconda3/envs/valle/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/speech/utkarsh/miniconda3/envs/valle/lib/python3.10/site-packages/wandb/sdk/interface/router.py", line 70, in message_loop
    msg = self._read_message()
  File "/speech/utkarsh/miniconda3/envs/valle/lib/python3.10/site-packages/wandb/sdk/interface/router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-03-04 18:13:11,333 INFO    MsgRouterThr:1557667 [mailbox.py:close():115] Closing mailbox, abandoning 1 handles.
