2025-03-05 02:16:28,620 INFO    Thread-3  :145045 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-05 02:16:28,620 INFO    Thread-3  :145045 [wandb_setup.py:_flush():67] Configure stats pid to 145045
2025-03-05 02:16:28,620 INFO    Thread-3  :145045 [wandb_setup.py:_flush():67] Loading settings from /speech/utkarsh/.config/wandb/settings
2025-03-05 02:16:28,620 INFO    Thread-3  :145045 [wandb_setup.py:_flush():67] Loading settings from /speech/utkarsh/da6401_assignment1/wandb/settings
2025-03-05 02:16:28,621 INFO    Thread-3  :145045 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-05 02:16:28,621 INFO    Thread-3  :145045 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /speech/utkarsh/da6401_assignment1/wandb/run-20250305_021628-mkwliubr/logs/debug.log
2025-03-05 02:16:28,621 INFO    Thread-3  :145045 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /speech/utkarsh/da6401_assignment1/wandb/run-20250305_021628-mkwliubr/logs/debug-internal.log
2025-03-05 02:16:28,621 INFO    Thread-3  :145045 [wandb_init.py:init():761] calling init triggers
2025-03-05 02:16:28,621 INFO    Thread-3  :145045 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'tanh', 'batch_size': 16, 'epochs': 2, 'hidden_layer_size': 32, 'hidden_layers_count': 2, 'learning_rate': 0.001, 'optimizer': 'adam', 'weight_decay': 0, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-03-05 02:16:28,621 INFO    Thread-3  :145045 [wandb_init.py:init():784] starting backend
2025-03-05 02:16:28,621 INFO    Thread-3  :145045 [wandb_init.py:init():788] sending inform_init request
2025-03-05 02:16:28,666 ERROR   Thread-3  :145045 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/speech/utkarsh/miniconda3/envs/deeplearn/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
  File "/speech/utkarsh/miniconda3/envs/deeplearn/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 790, in init
    settings=settings.to_proto(),
  File "/speech/utkarsh/miniconda3/envs/deeplearn/lib/python3.8/site-packages/wandb/sdk/wandb_settings.py", line 1421, in to_proto
    for k, v in self.model_dump(exclude_none=True).items():
  File "/speech/utkarsh/miniconda3/envs/deeplearn/lib/python3.8/site-packages/pydantic/main.py", line 426, in model_dump
    return self.__pydantic_serializer__.to_python(
  File "/speech/utkarsh/miniconda3/envs/deeplearn/lib/python3.8/site-packages/wandb/sdk/wandb_settings.py", line 1053, in _os
    return platform.platform(aliased=True)
  File "/speech/utkarsh/miniconda3/envs/deeplearn/lib/python3.8/platform.py", line 1206, in platform
    libcname, libcversion = libc_ver(sys.executable)
  File "/speech/utkarsh/miniconda3/envs/deeplearn/lib/python3.8/platform.py", line 202, in libc_ver
    chunk = f.read(chunksize)
Exception
